apiVersion: apps/v1
kind: Deployment
metadata:
  name: microserviceapplication
  labels:
    app: microserviceapplication
    kubernetes.azure.com/generator: devhub
  namespace: aks-store-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microserviceapplication
  template:
    metadata:
      labels:
        app: microserviceapplication
    spec:
      containers:
        - name: microserviceapplication
          image: acrspotwesteuprd01.azurecr.io/aksstoredemo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
