apiVersion: v1
kind: Service
metadata:
  name: microserviceapplication
  namespace: aks-store-demo
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: microserviceapplication
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000